"""
Claude-Enhanced MCP Server Generator.

Combines the standard MCP server generation with Claude's analysis
to produce significantly better MCP servers with:
  - Rich, action-oriented tool descriptions
  - Usage examples per tool
  - Error handling notes
  - Logical tool grouping
  - Test case generation
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

from mcp_anything.analyzer import OpenAPIAnalyzer
from mcp_anything.claude import ClaudeIntegration, ClaudeEnhancedEndpoint, ToolGroup
from mcp_anything.generator import MCPServerGenerator, _sanitize_name


# ─── Enhanced Templates ─────────────────────────────────────────────────────

ENHANCED_SERVER_HEADER = '''"""
{name} - MCP Server (Claude-Enhanced)
Auto-generated by MCP-Anything from {spec_source}
Enhanced by Claude ({claude_model})

Title: {title}
Version: {version}
Base URL: {base_url}
Tools: {tool_count}
Groups: {group_count}
"""

import json
import os
from typing import Any, Literal, Optional

import httpx
from fastmcp import FastMCP

# ─── Configuration ──────────────────────────────────────────────────────

BASE_URL = os.environ.get("{env_prefix}_BASE_URL", "{base_url}")
API_KEY = os.environ.get("{env_prefix}_API_KEY", "")

# ─── HTTP Client ────────────────────────────────────────────────────────

def _get_headers() -> dict:
    headers = {{"Content-Type": "application/json", "Accept": "application/json"}}
    if API_KEY:
        headers["Authorization"] = f"Bearer {{API_KEY}}"
    return headers

def _request(method: str, path: str, params: dict = None, body: dict = None) -> dict:
    """Make an HTTP request and return structured JSON."""
    url = BASE_URL.rstrip("/") + path
    with httpx.Client(timeout=30) as client:
        resp = client.request(
            method=method,
            url=url,
            params=params or {{}},
            json=body if body else None,
            headers=_get_headers(),
        )
        resp.raise_for_status()
        if resp.status_code == 204:
            return {{"status": "success", "code": 204}}
        try:
            return resp.json()
        except Exception:
            return {{"status": "success", "text": resp.text[:2000]}}

# ─── MCP Server ─────────────────────────────────────────────────────────

mcp = FastMCP("{name}")

'''


def _build_enhanced_tool(
    ep: ClaudeEnhancedEndpoint,
    base_url: str,
) -> str:
    """Generate an enhanced MCP tool function from a Claude-analyzed endpoint."""
    func_name = ep.tool_name or _sanitize_name(ep.operation_id)

    # Build parameter signature
    params_parts = []
    path_params = [p for p in ep.parameters if p.get("location") == "path"]
    query_params = [p for p in ep.parameters if p.get("location") == "query"]

    for p in path_params:
        py_type = _schema_to_type(p.get("schema", {}))
        params_parts.append(f"{_sanitize_name(p['name'])}: {py_type}")

    for p in query_params:
        py_type = _schema_to_type(p.get("schema", {}))
        required = p.get("required", False)
        if required:
            params_parts.append(f"{_sanitize_name(p['name'])}: {py_type}")
        else:
            default = _schema_default(p.get("schema", {}))
            params_parts.append(f"{_sanitize_name(p['name'])}: {py_type} = {default}")

    if ep.request_body:
        params_parts.append("body: dict = {}")

    params_str = ", ".join(params_parts)

    # Build docstring
    doc_lines = []
    desc = ep.enhanced_description or ep.original_summary or f"{ep.method} {ep.path}"
    doc_lines.append(desc)

    if ep.prerequisites:
        doc_lines.append(f"\nPrerequisites: {ep.prerequisites}")

    # Parameter docs
    if ep.parameter_docs:
        doc_lines.append("\nArgs:")
        for pname, pdoc in ep.parameter_docs.items():
            line = f"    {_sanitize_name(pname)}: {pdoc.get('description', '')}"
            if pdoc.get("example"):
                line += f" (e.g., {pdoc['example']})"
            if pdoc.get("constraints"):
                line += f" [{pdoc['constraints']}]"
            doc_lines.append(line)
    else:
        # Fall back to basic param docs
        for p in ep.parameters:
            doc_lines.append(f"    {_sanitize_name(p['name'])}: {p.get('description', p['name'])}")

    if ep.request_body:
        doc_lines.append("    body: Request body as a JSON-serializable dict")

    # Usage examples
    if ep.usage_examples:
        doc_lines.append("\nExamples:")
        for ex in ep.usage_examples[:2]:
            doc_lines.append(f"    {ex.get('scenario', 'Example')}:")
            doc_lines.append(f"        params: {json.dumps(ex.get('params', {}))}")

    # Error scenarios
    if ep.error_scenarios:
        doc_lines.append("\nError Handling:")
        for err in ep.error_scenarios[:3]:
            code = err.get("status_code", "")
            code_str = f" (HTTP {code})" if code else ""
            doc_lines.append(f"    - {err['condition']}{code_str}: {err['handling']}")

    doc_string = "\n".join(doc_lines)

    # Build body
    body_lines = []

    # URL with path params
    path = ep.path
    for p in path_params:
        sname = _sanitize_name(p["name"])
        path = path.replace(f"{{{p['name']}}}", f"{{{sname}}}")
    body_lines.append(f'    path = f"{path}"')

    # Query params
    if query_params:
        body_lines.append("    query_params = {}")
        for p in query_params:
            sname = _sanitize_name(p["name"])
            body_lines.append(f"    if {sname} is not None and {sname} != '':")
            body_lines.append(f'        query_params["{p["name"]}"] = {sname}')
    else:
        body_lines.append("    query_params = {}")

    # Request body
    if ep.request_body:
        body_lines.append("    request_body = body if body else None")
    else:
        body_lines.append("    request_body = None")

    # Make request
    body_lines.append(
        f'    return _request("{ep.method}", path, params=query_params, body=request_body)'
    )

    body_str = "\n".join(body_lines)

    return f'''@mcp.tool()
def {func_name}({params_str}) -> dict:
    """{doc_string}"""
{body_str}

'''


def _schema_to_type(schema: dict) -> str:
    """Convert JSON Schema to Python type."""
    t = schema.get("type", "any")
    if "enum" in schema:
        vals = schema["enum"]
        if all(isinstance(v, str) for v in vals):
            return f"Literal[{', '.join(repr(v) for v in vals)}]"
    type_map = {
        "string": "str", "integer": "int", "number": "float",
        "boolean": "bool", "array": "list", "object": "dict",
    }
    return type_map.get(t, "Any")


def _schema_default(schema: dict) -> str:
    """Get default value for optional param."""
    if "default" in schema:
        return repr(schema["default"])
    t = schema.get("type", "any")
    defaults = {"string": '""', "integer": "0", "number": "0.0", "boolean": "False", "array": "[]", "object": "{}"}
    return defaults.get(t, "None")


class ClaudeEnhancedGenerator:
    """Generate MCP servers with Claude-powered enhancement."""

    def __init__(
        self,
        analyzer: OpenAPIAnalyzer,
        api_key: str = "",
        model: str = "claude-sonnet-4-20250514",
        batch_size: int = 5,
    ):
        self.analyzer = analyzer
        self.claude = ClaudeIntegration(api_key=api_key, model=model)
        self.batch_size = batch_size

    def generate(
        self,
        output_dir: str,
        server_name: str = "",
        env_prefix: str = "",
        include_groups: bool = True,
        include_tests: bool = False,
        on_progress: callable = None,
    ) -> dict:
        """Generate a Claude-enhanced MCP server.

        Args:
            output_dir: Where to write the generated files
            server_name: Name for the MCP server
            env_prefix: Environment variable prefix
            include_groups: Whether to generate tool group documentation
            include_tests: Whether to generate test cases
            on_progress: Progress callback(step, detail)

        Returns:
            dict with paths to generated files
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # Step 1: Parse spec
        if on_progress:
            on_progress("analyze", "Parsing OpenAPI spec...")
        endpoints = self.analyzer.extract_endpoints()
        summary = self.analyzer.summary()
        server_name = server_name or self._derive_name(summary)

        # Step 2: Convert to dicts for Claude
        endpoint_dicts = self._endpoints_to_dicts(endpoints)

        # Step 3: Claude enhancement
        if on_progress:
            on_progress("enhance", f"Analyzing {len(endpoints)} endpoints with Claude...")

        result = self.claude.enhance_with_claude(
            endpoints=endpoint_dicts,
            api_context=summary,
            include_groups=include_groups,
            include_tests=include_tests,
            batch_size=self.batch_size,
        )

        enhanced = result["enhanced_endpoints"]
        groups = result["groups"]

        if on_progress:
            on_progress("generate", f"Generating server code for {len(enhanced)} tools...")

        # Step 4: Generate server code
        tool_code = []
        for ep in enhanced:
            tool_code.append(_build_enhanced_tool(ep, summary["base_url"]))

        env_prefix = env_prefix or server_name.upper().replace("-", "_").replace(" ", "_")

        server_code = ENHANCED_SERVER_HEADER.format(
            name=server_name,
            spec_source=self.analyzer.spec_source[:100],
            claude_model=self.claude.model,
            title=summary["title"],
            version=summary["version"],
            base_url=summary["base_url"],
            tool_count=len(enhanced),
            group_count=len(groups),
            env_prefix=env_prefix,
        ) + "\n".join(tool_code)

        # Step 5: Write files
        if on_progress:
            on_progress("write", "Writing generated files...")

        # Server file
        server_file = output_path / f"{_sanitize_name(server_name)}_server.py"
        server_file.write_text(server_code)

        # MCP config
        config = {
            "mcpServers": {
                server_name: {
                    "command": "python3",
                    "args": [str(server_file)],
                    "env": {
                        f"{env_prefix}_BASE_URL": f"${{{env_prefix}_BASE_URL}}",
                        f"{env_prefix}_API_KEY": f"${{{env_prefix}_API_KEY}}",
                    },
                }
            }
        }
        config_file = output_path / "mcp_config.json"
        config_file.write_text(json.dumps(config, indent=2))

        # Enhanced inventory
        inventory = []
        for ep in enhanced:
            inventory.append({
                "name": ep.tool_name,
                "operation_id": ep.operation_id,
                "method": ep.method,
                "path": ep.path,
                "description": ep.enhanced_description or ep.original_summary,
                "tags": ep.tags,
                "examples": ep.usage_examples,
                "error_scenarios": ep.error_scenarios,
                "prerequisites": ep.prerequisites,
                "related_tools": ep.related_tools,
            })
        inventory_file = output_path / "tools_inventory.json"
        inventory_file.write_text(json.dumps(inventory, indent=2))

        # Groups documentation
        if groups:
            groups_doc = self._generate_groups_doc(groups, enhanced)
            groups_file = output_path / "TOOL_GROUPS.md"
            groups_file.write_text(groups_doc)

        # Test cases
        if result["tests"]:
            tests_file = output_path / "test_cases.json"
            tests_file.write_text(json.dumps(result["tests"], indent=2))

        # .env example
        env_file = output_path / ".env.example"
        env_file.write_text(
            f"# {server_name} MCP Server (Claude-Enhanced)\n"
            f"{env_prefix}_BASE_URL={summary['base_url']}\n"
            f"{env_prefix}_API_KEY=\n"
        )

        # README
        readme = self._generate_readme(summary, enhanced, groups, result["summary"])
        readme_file = output_path / "README.md"
        readme_file.write_text(readme)

        if on_progress:
            on_progress("done", f"Generated {len(enhanced)} enhanced tools")

        return {
            "server_file": str(server_file),
            "config_file": str(config_file),
            "inventory_file": str(inventory_file),
            "tool_count": len(enhanced),
            "group_count": len(groups),
            "server_name": server_name,
            "claude_model": self.claude.model,
            "enhancement_summary": result["summary"],
        }

    def _derive_name(self, summary: dict) -> str:
        title = summary.get("title", "api")
        return re.sub(r'[^a-zA-Z0-9_-]', '-', title.lower()).strip('-') or "generated-api"

    def _endpoints_to_dicts(self, endpoints) -> list[dict]:
        result = []
        for ep in endpoints:
            result.append({
                "operation_id": ep.operation_id,
                "method": ep.method,
                "path": ep.path,
                "summary": ep.summary,
                "description": ep.description,
                "tags": ep.tags,
                "parameters": [
                    {
                        "name": p.name,
                        "location": p.location,
                        "required": p.required,
                        "schema": p.schema,
                        "description": p.description,
                    }
                    for p in ep.parameters
                ],
                "request_body": ep.request_body,
                "response_schema": ep.response_schema,
            })
        return result

    def _generate_groups_doc(self, groups: list[ToolGroup], enhanced: list[ClaudeEnhancedEndpoint]) -> str:
        # Build tool name lookup
        tool_names = {ep.operation_id: ep.tool_name for ep in enhanced}

        lines = ["# Tool Groups\n"]
        lines.append("Logical groupings of related tools for common workflows.\n")

        for group in groups:
            lines.append(f"\n## {group.name}\n")
            lines.append(f"{group.description}\n")

            if group.common_workflow:
                lines.append(f"**Typical workflow:** {group.common_workflow}\n")

            lines.append("\n| Tool | Description |")
            lines.append("|------|-------------|")
            for op_id in group.tools:
                name = tool_names.get(op_id, op_id)
                ep = next((e for e in enhanced if e.operation_id == op_id), None)
                desc = (ep.enhanced_description if ep else "")[:80] or "-"
                lines.append(f"| `{name}` | {desc} |")

        return "\n".join(lines)

    def _generate_readme(self, summary, enhanced, groups, enh_summary) -> str:
        lines = [
            f"# {summary['title']} MCP Server (Claude-Enhanced)\n",
            f"Auto-generated by **MCP-Anything**, enhanced by **Claude** ({enh_summary.get('model', '')}).\n",
            f"**API:** {summary['title']} v{summary['version']}",
            f"**Base URL:** `{summary['base_url']}`",
            f"**Tools:** {len(enhanced)} (Claude-enhanced)",
            f"**Groups:** {len(groups)} logical workflows",
            "",
            "## Enhancement Statistics\n",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total tools | {enh_summary.get('total_endpoints', 0)} |",
            f"| With usage examples | {enh_summary.get('with_examples', 0)} |",
            f"| With error handling | {enh_summary.get('with_error_handling', 0)} |",
            f"| With prerequisites | {enh_summary.get('with_prerequisites', 0)} |",
            f"| Tool groups | {enh_summary.get('groups_suggested', 0)} |",
            "",
            "## Tools\n",
            "| Tool | Method | Path | Description |",
            "|------|--------|------|-------------|",
        ]

        for ep in enhanced[:50]:  # Cap at 50 for readability
            desc = (ep.enhanced_description or ep.original_summary or "-")[:60]
            lines.append(f"| `{ep.tool_name}` | {ep.method} | `{ep.path}` | {desc} |")

        if len(enhanced) > 50:
            lines.append(f"\n*... and {len(enhanced) - 50} more tools. See tools_inventory.json for full list.*")

        if groups:
            lines.append("\n## Tool Groups\n")
            for g in groups:
                lines.append(f"- **{g.name}**: {g.description} ({len(g.tools)} tools)")

        lines.append("\n## Setup\n")
        lines.append("```bash")
        lines.append("cp .env.example .env")
        lines.append("# Edit .env with your API credentials")
        lines.append("```")
        lines.append("")
        lines.append("See `mcp_config.json` for MCP client configuration.")

        return "\n".join(lines)
