"""MCP Server Generator - converts OpenAPI endpoints into a working FastMCP server."""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path
from typing import Optional

from mcp_anything.analyzer import OpenAPIAnalyzer, EndpointInfo


# ─── Python code generation helpers ──────────────────────────────────────────

def _sanitize_name(name: str) -> str:
    """Make a string safe as a Python identifier."""
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    name = re.sub(r'_+', '_', name).strip('_')
    if name and name[0].isdigit():
        name = f"op_{name}"
    return name.lower()


def _schema_to_python_type(schema: dict) -> str:
    """Convert a JSON Schema type hint to a Python type annotation string."""
    if not schema:
        return "Any"

    t = schema.get("type", "any")

    if "enum" in schema:
        vals = schema["enum"]
        if all(isinstance(v, str) for v in vals):
            return f"Literal[{', '.join(repr(v) for v in vals)}]"
        return "Any"

    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": f"list[{_schema_to_python_type(schema.get('items', {}))}]",
        "object": "dict",
    }
    return type_map.get(t, "Any")


def _schema_to_default(schema: dict, required: bool) -> str:
    """Generate default value expression for a parameter."""
    if required:
        return ""
    if "default" in schema:
        return f" = {repr(schema['default'])}"
    type_defaults = {
        "string": ' = ""',
        "integer": " = 0",
        "number": " = 0.0",
        "boolean": " = False",
        "array": " = []",
        "object": " = {}",
    }
    return type_defaults.get(schema.get("type", ""), " = None")


def _build_param_signature(endpoint: EndpointInfo) -> str:
    """Build the Python function parameter list for an endpoint."""
    parts = []

    # Path parameters first (always required)
    path_params = [p for p in endpoint.parameters if p.location == "path"]
    for p in path_params:
        py_type = _schema_to_python_type(p.schema)
        parts.append(f"{_sanitize_name(p.name)}: {py_type}")

    # Query parameters
    query_params = [p for p in endpoint.parameters if p.location == "query"]
    for p in query_params:
        py_type = _schema_to_python_type(p.schema)
        default = _schema_to_default(p.schema, p.required)
        parts.append(f"{_sanitize_name(p.name)}: {py_type}{default}")

    # Request body as a single dict param
    if endpoint.request_body:
        parts.append("body: dict = {}")

    return ", ".join(parts)


def _build_url_template(path: str, parameters: list) -> str:
    """Convert OpenAPI path template to f-string template with sanitized names."""
    # Build mapping: original_name -> sanitized_name
    name_map = {}
    for p in parameters:
        if p.location == "path":
            name_map[p.name] = _sanitize_name(p.name)
    
    def replacer(m):
        orig = m.group(1)
        return '{' + name_map.get(orig, _sanitize_name(orig)) + '}'
    
    return re.sub(r'\{(\w+)\}', replacer, path)


def _build_query_params(endpoint: EndpointInfo) -> str:
    """Generate query parameter construction code."""
    query_params = [p for p in endpoint.parameters if p.location == "query"]
    if not query_params:
        return "    query_params = {}"

    lines = ["    query_params = {}"]
    for p in query_params:
        var_name = _sanitize_name(p.name)
        lines.append(f"    if {var_name} is not None and {var_name} != '':")
        lines.append(f'        query_params["{p.name}"] = {var_name}')

    return "\n".join(lines)


# ─── Server code template ───────────────────────────────────────────────────

SERVER_TEMPLATE = '''"""
{name} - MCP Server
Auto-generated by MCP-Anything from {spec_source}

Title: {title}
Version: {version}
Base URL: {base_url}
Endpoints: {endpoint_count}
"""

import json
import os
from typing import Any, Literal, Optional

import httpx
from fastmcp import FastMCP

# ─── Configuration ──────────────────────────────────────────────────────

BASE_URL = os.environ.get("{env_prefix}_BASE_URL", "{base_url}")
API_KEY = os.environ.get("{env_prefix}_API_KEY", "")

# ─── HTTP Client ────────────────────────────────────────────────────────

def _get_headers() -> dict:
    headers = {{"Content-Type": "application/json", "Accept": "application/json"}}
    if API_KEY:
        headers["Authorization"] = f"Bearer {{API_KEY}}"
    return headers

def _request(method: str, path: str, params: dict = None, body: dict = None) -> dict:
    """Make an HTTP request and return parsed JSON."""
    url = BASE_URL.rstrip("/") + path
    with httpx.Client(timeout=30) as client:
        resp = client.request(
            method=method,
            url=url,
            params=params or {{}},
            json=body if body else None,
            headers=_get_headers(),
        )
        resp.raise_for_status()
        if resp.status_code == 204:
            return {{"status": "success", "code": 204}}
        try:
            return resp.json()
        except Exception:
            return {{"status": "success", "text": resp.text[:2000]}}

# ─── MCP Server ─────────────────────────────────────────────────────────

mcp = FastMCP("{name}")

{tool_definitions}
'''

TOOL_TEMPLATE = '''@mcp.tool()
def {func_name}({params}) -> dict:
    """
    {summary}
    
    {description}
{param_docs}
    """
{body}
'''


class MCPServerGenerator:
    """Generate a complete FastMCP server from an OpenAPI spec."""

    def __init__(
        self,
        analyzer: OpenAPIAnalyzer,
        server_name: str = "",
        env_prefix: str = "",
    ):
        self.analyzer = analyzer
        self.server_name = server_name or self._derive_server_name()
        self.env_prefix = env_prefix or self.server_name.upper().replace("-", "_").replace(" ", "_")

    def _derive_server_name(self) -> str:
        summary = self.analyzer.summary()
        title = summary.get("title", "api")
        return re.sub(r'[^a-zA-Z0-9_-]', '-', title.lower()).strip('-') or "generated-api"

    def generate(self, output_dir: str = "./output") -> dict:
        """Generate the complete MCP server package.

        Returns:
            dict with paths to generated files.
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        endpoints = self.analyzer.extract_endpoints()
        summary = self.analyzer.summary()

        # Generate tool definitions
        tool_lines = []
        for ep in endpoints:
            tool_code = self._generate_tool(ep)
            tool_lines.append(tool_code)

        # Generate server code
        server_code = SERVER_TEMPLATE.format(
            name=self.server_name,
            spec_source=self.analyzer.spec_source[:100],
            title=summary["title"],
            version=summary["version"],
            base_url=summary["base_url"],
            endpoint_count=summary["endpoint_count"],
            env_prefix=self.env_prefix,
            tool_definitions="\n".join(tool_lines),
        )

        # Write server file
        server_file = output_path / f"{_sanitize_name(self.server_name)}_server.py"
        server_file.write_text(server_code)

        # Write config for MCP clients
        config = self._generate_mcp_config(str(server_file))
        config_file = output_path / "mcp_config.json"
        config_file.write_text(json.dumps(config, indent=2))

        # Write tool inventory
        inventory = self._generate_inventory(endpoints)
        inventory_file = output_path / "tools_inventory.json"
        inventory_file.write_text(json.dumps(inventory, indent=2))

        # Write env template
        env_file = output_path / ".env.example"
        env_file.write_text(
            f"# {self.server_name} MCP Server Configuration\n"
            f"{self.env_prefix}_BASE_URL={summary['base_url']}\n"
            f"{self.env_prefix}_API_KEY=\n"
        )

        # Write README
        readme = self._generate_readme(summary, endpoints)
        readme_file = output_path / "README.md"
        readme_file.write_text(readme)

        return {
            "server_file": str(server_file),
            "config_file": str(config_file),
            "inventory_file": str(inventory_file),
            "env_file": str(env_file),
            "readme_file": str(readme_file),
            "tool_count": len(endpoints),
            "server_name": self.server_name,
        }

    def _generate_tool(self, ep: EndpointInfo) -> str:
        """Generate a single MCP tool function."""
        func_name = _sanitize_name(ep.operation_id) or _sanitize_name(f"{ep.method}_{ep.path}")

        # Parameter signature
        params = _build_param_signature(ep)

        # Docstring
        summary = ep.summary or f"{ep.method} {ep.path}"
        description = ep.description or ""

        # Param docs
        param_docs = []
        for p in ep.parameters:
            loc = p.location
            req = "required" if p.required else "optional"
            desc = p.description or f"{p.name} ({loc}, {req})"
            param_docs.append(f"        {_sanitize_name(p.name)}: {desc}")
        if ep.request_body:
            param_docs.append("        body: Request body as a dict")

        param_doc_str = "\n".join(param_docs)

        # Body - build the HTTP request
        body_lines = []

        # URL construction
        path_templated = _build_url_template(ep.path, ep.parameters)
        body_lines.append(f'    path = f"{path_templated}"')

        # Query params
        body_lines.append(_build_query_params(ep))

        # Request body
        if ep.request_body:
            body_lines.append("    request_body = body if body else None")
        else:
            body_lines.append("    request_body = None")

        # Make the request
        body_lines.append(
            f'    return _request("{ep.method}", path, '
            f"params=query_params, body=request_body)"
        )

        body = "\n".join(body_lines)

        return TOOL_TEMPLATE.format(
            func_name=func_name,
            params=params,
            summary=summary,
            description=description,
            param_docs=param_doc_str,
            body=body,
        )

    def _generate_mcp_config(self, server_file: str) -> dict:
        """Generate MCP client config block."""
        return {
            "mcpServers": {
                self.server_name: {
                    "command": "python3",
                    "args": [server_file],
                    "env": {
                        f"{self.env_prefix}_BASE_URL": f"${{{self.env_prefix}_BASE_URL}}",
                        f"{self.env_prefix}_API_KEY": f"${{{self.env_prefix}_API_KEY}}",
                    },
                }
            }
        }

    def _generate_inventory(self, endpoints: list[EndpointInfo]) -> list[dict]:
        """Generate a JSON inventory of all tools."""
        inventory = []
        for ep in endpoints:
            func_name = _sanitize_name(ep.operation_id) or _sanitize_name(f"{ep.method}_{ep.path}")
            inventory.append({
                "name": func_name,
                "operation_id": ep.operation_id,
                "method": ep.method,
                "path": ep.path,
                "summary": ep.summary,
                "tags": ep.tags,
                "parameters": [
                    {
                        "name": _sanitize_name(p.name),
                        "original_name": p.name,
                        "location": p.location,
                        "required": p.required,
                        "type": _schema_to_python_type(p.schema),
                    }
                    for p in ep.parameters
                ],
                "has_request_body": ep.request_body is not None,
            })
        return inventory

    def _generate_readme(self, summary: dict, endpoints: list[EndpointInfo]) -> str:
        """Generate a README for the generated MCP server."""
        tag_groups = {}
        for ep in endpoints:
            for tag in ep.tags or ["untagged"]:
                tag_groups.setdefault(tag, []).append(ep)

        tools_section = ""
        for tag, eps in sorted(tag_groups.items()):
            tools_section += f"\n### {tag}\n\n"
            tools_section += "| Tool | Method | Path | Description |\n"
            tools_section += "|------|--------|------|-------------|\n"
            for ep in eps:
                name = _sanitize_name(ep.operation_id)
                desc = ep.summary or ep.description or "-"
                tools_section += f"| `{name}` | {ep.method} | `{ep.path}` | {desc[:80]} |\n"

        return textwrap.dedent(f"""\
        # {self.server_name} MCP Server

        Auto-generated by **MCP-Anything** from OpenAPI spec.

        **API:** {summary['title']} v{summary['version']}  
        **Base URL:** `{summary['base_url']}`  
        **Tools:** {summary['endpoint_count']} endpoints  

        ## Setup

        1. Copy `.env.example` to `.env` and fill in your credentials:
           ```bash
           cp .env.example .env
           ```

        2. Add to your MCP client config (`mcp_config.json`):
           ```json
           {json.dumps(self._generate_mcp_config("server.py"), indent=2)}
           ```

        3. Install dependencies:
           ```bash
           pip install fastmcp httpx
           ```

        ## Available Tools
        {tools_section}
        """)
