"""MCP Server Generator - converts OpenAPI endpoints into a working FastMCP server."""

from __future__ import annotations

import hashlib
import inspect
import json
import keyword
import re
import textwrap
from pathlib import Path
from typing import Iterable, Optional

from mcp_anything.analyzer import EndpointInfo, OpenAPIAnalyzer, ParameterInfo
from mcp_anything import runtime as runtime_module
from mcp_anything.runtime import SAFE_METHODS
from mcp_anything.skill_gen import SkillGenerator


# ─── Python code generation helpers ──────────────────────────────────────────

def _sanitize_name(name: str) -> str:
    """Make a string safe as a Python identifier."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    if name and name[0].isdigit():
        name = f"op_{name}"
    name = name.lower()
    return f"_{name}" if keyword.iskeyword(name) else name


def _schema_to_python_type(schema: dict) -> str:
    """Convert a JSON Schema type hint to a Python type annotation string."""
    if not schema:
        return "Any"

    if "enum" in schema:
        vals = schema["enum"]
        if all(isinstance(v, str) for v in vals):
            return f"Literal[{', '.join(repr(v) for v in vals)}]"
        return "Any"

    schema_type = schema.get("type", "any")
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "object": "dict",
    }
    if schema_type == "array":
        return f"list[{_schema_to_python_type(schema.get('items', {}))}]"
    return type_map.get(schema_type, "Any")


def _schema_to_default(schema: dict, required: bool) -> str:
    """Generate a safe default value expression for a parameter."""
    if required:
        return ""
    if "default" in schema:
        return f" = {repr(schema['default'])}"
    # None avoids mutable defaults and preserves omitted-vs-present semantics.
    return " = None"


def _parameter_bindings(
    endpoint: EndpointInfo,
) -> tuple[list[tuple[ParameterInfo, str]], Optional[str]]:
    """Allocate unique local names for all parameters and the request body."""
    used = {"path", "query_params", "header_params", "cookie_params", "request_body"}
    bindings: list[tuple[ParameterInfo, str]] = []

    for parameter in endpoint.parameters:
        base = _sanitize_name(parameter.name) or "param"
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base}_{suffix}"
            suffix += 1
        used.add(candidate)
        bindings.append((parameter, candidate))

    body_name = None
    if endpoint.request_body:
        body_name = "body"
        suffix = 2
        while body_name in used:
            body_name = f"body_{suffix}"
            suffix += 1
    return bindings, body_name


def _build_param_signature(endpoint: EndpointInfo) -> str:
    """Build the Python function parameter list for an endpoint."""
    bindings, body_name = _parameter_bindings(endpoint)
    parts: list[tuple[int, str]] = []
    for parameter, local_name in bindings:
        required = parameter.required or parameter.location == "path"
        default = _schema_to_default(parameter.schema, required)
        parts.append((0 if required else 1, f"{local_name}: {_schema_to_python_type(parameter.schema)}{default}"))
    if body_name:
        parts.append((2, f"{body_name}: dict = None"))
    parts.sort(key=lambda item: item[0])
    return ", ".join(part for _, part in parts)


def _build_url_template(path: str, parameters: list) -> str:
    """Convert OpenAPI path templates to URL-encoded f-string expressions."""
    name_map = {}
    for item in parameters:
        parameter = item[0] if isinstance(item, tuple) else item
        local_name = item[1] if isinstance(item, tuple) else _sanitize_name(parameter.name)
        if parameter.location == "path":
            name_map[parameter.name] = local_name

    def replacer(match: re.Match[str]) -> str:
        local_name = name_map.get(match.group(1), _sanitize_name(match.group(1)))
        return "{quote(str(" + local_name + "), safe='')}"

    return re.sub(r"\{(\w+)\}", replacer, path)


def _build_parameter_map(
    bindings: list[tuple[ParameterInfo, str]],
    location: str,
    variable_name: str,
) -> str:
    lines = [f"    {variable_name} = {{}}"]
    for parameter, local_name in bindings:
        if parameter.location != location:
            continue
        lines.append(f"    if {local_name} is not None:")
        lines.append(f"        {variable_name}[{json.dumps(parameter.name)}] = {local_name}")
    return "\n".join(lines)


# ─── Server code template ───────────────────────────────────────────────────

SERVER_TEMPLATE = '''"""{name} - MCP Server
Auto-generated by MCP-Anything from {spec_source}

Title: {title}
Version: {version}
Base URL: {base_url}
Endpoints: {endpoint_count}
"""

import os
from typing import Any, Literal
from urllib.parse import quote

from fastmcp import FastMCP
from mcp_runtime import AuthSession, CapabilityPolicy, MCPHttpClient

BASE_URL = os.environ.get("{env_prefix}_BASE_URL", "{base_url}")
AUTH = AuthSession(
    BASE_URL,
    email=os.environ.get("{env_prefix}_EMAIL", ""),
    password=os.environ.get("{env_prefix}_PASSWORD", ""),
    static_token=os.environ.get("{env_prefix}_API_KEY", ""),
)
POLICY = CapabilityPolicy.from_env("{env_prefix}")
HTTP = MCPHttpClient(AUTH, POLICY)


def _request(
    method: str,
    path: str,
    *,
    params: dict | None = None,
    headers: dict | None = None,
    cookies: dict | None = None,
    body: dict | None = None,
    content_type: str = "application/json",
    operation_id: str = "",
    tags: list[str] | None = None,
) -> dict:
    return HTTP.request(
        method,
        path,
        params=params,
        headers=headers,
        cookies=cookies,
        body=body,
        content_type=content_type,
        operation_id=operation_id,
        tags=tags,
    )


mcp = FastMCP("{name}")

{tool_definitions}


if __name__ == "__main__":
    mcp.run()
'''




class MCPServerGenerator:
    """Generate a complete, policy-controlled FastMCP server."""

    def __init__(
        self,
        analyzer: OpenAPIAnalyzer,
        server_name: str = "",
        env_prefix: str = "",
        *,
        allow_writes: bool = False,
        allowed_tags: Optional[set[str]] = None,
        allowed_operations: Optional[set[str]] = None,
        denied_operations: Optional[set[str]] = None,
        allowed_methods: Optional[set[str]] = None,
        max_documented_tools: int = 500,
    ):
        self.analyzer = analyzer
        self.server_name = server_name or self._derive_server_name()
        self.env_prefix = env_prefix or self.server_name.upper().replace("-", "_").replace(" ", "_")
        self.allow_writes = allow_writes
        self.allowed_tags = {tag for tag in (allowed_tags or set()) if tag}
        self.allowed_operations = {op for op in (allowed_operations or set()) if op}
        self.denied_operations = {op for op in (denied_operations or set()) if op}
        self.allowed_methods = {
            method.upper() for method in (allowed_methods or set()) if method
        }
        self.max_documented_tools = max_documented_tools

    def _derive_server_name(self) -> str:
        title = self.analyzer.summary().get("title", "api")
        return re.sub(r"[^a-zA-Z0-9_-]", "-", title.lower()).strip("-") or "generated-api"

    def _filter_endpoints(self, endpoints: list[EndpointInfo]) -> list[EndpointInfo]:
        result = []
        for endpoint in endpoints:
            if self.allowed_methods and endpoint.method not in self.allowed_methods:
                continue
            if not self.allow_writes and endpoint.method not in SAFE_METHODS:
                continue
            if self.allowed_tags and not self.allowed_tags.intersection(endpoint.tags):
                continue
            if self.allowed_operations and endpoint.operation_id not in self.allowed_operations:
                continue
            if endpoint.operation_id in self.denied_operations:
                continue
            result.append(endpoint)
        return result

    def generate(self, output_dir: str = "./output") -> dict:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        all_endpoints = self.analyzer.extract_endpoints()
        endpoints = self._filter_endpoints(all_endpoints)
        summary = self.analyzer.summary()
        summary["endpoint_count"] = len(endpoints)

        tool_lines = [self._generate_tool(endpoint) for endpoint in endpoints]
        server_code = SERVER_TEMPLATE.format(
            name=self.server_name,
            spec_source=self.analyzer.spec_source[:100],
            title=summary["title"],
            version=summary["version"],
            base_url=summary["base_url"],
            endpoint_count=len(endpoints),
            env_prefix=self.env_prefix,
            tool_definitions="\n".join(tool_lines),
        )

        server_file = output_path / f"{_sanitize_name(self.server_name)}_server.py"
        server_file.write_text(server_code)
        compile(server_code, str(server_file), "exec")

        runtime_file = output_path / "mcp_runtime.py"
        runtime_source = Path(inspect.getfile(runtime_module)).read_text()
        compile(runtime_source, str(runtime_file), "exec")
        runtime_file.write_text(runtime_source)
        config_file = output_path / "mcp_config.json"
        config_file.write_text(json.dumps(self._generate_mcp_config(str(server_file)), indent=2))

        inventory = self._generate_inventory(endpoints)
        inventory_file = output_path / "tools_inventory.json"
        inventory_file.write_text(json.dumps(self._generate_inventory(endpoints), indent=2))

        env_file = output_path / ".env.example"
        env_file.write_text(
            f"# {self.server_name} MCP Server Configuration\n"
            f"{self.env_prefix}_BASE_URL={summary['base_url']}\n"
            f"{self.env_prefix}_EMAIL=\n"
            f"{self.env_prefix}_PASSWORD=\n"
            f"{self.env_prefix}_API_KEY=\n"
            f"{self.env_prefix}_ALLOW_WRITES={'true' if self.allow_writes else 'false'}\n"
            f"{self.env_prefix}_ALLOWED_METHODS={','.join(sorted(self.allowed_methods))}\n"
            f"{self.env_prefix}_ALLOWED_TAGS=\n"
            f"{self.env_prefix}_ALLOWED_OPERATIONS=\n"
            f"{self.env_prefix}_DENIED_OPERATIONS=\n"
        )

        documented_endpoints = endpoints[: self.max_documented_tools]
        readme_file = output_path / "README.md"
        readme_file.write_text(self._generate_readme(summary, endpoints, documented_endpoints))

        skill_file = output_path / "SKILL.md"
        SkillGenerator(self.analyzer, server_name=self.server_name).generate(
            documented_endpoints,
            output_path,
        )

        manifest = {
            "generator": "mcp-anything",
            "spec_source": self.analyzer.spec_source,
            "spec_sha256": hashlib.sha256(
                Path(self.analyzer.spec_source).read_bytes()
                if Path(self.analyzer.spec_source).exists()
                else self.analyzer.spec_source.encode()
            ).hexdigest(),
            "server_name": self.server_name,
            "endpoint_count": len(endpoints),
            "source_endpoint_count": len(all_endpoints),
            "allow_writes": self.allow_writes,
            "allowed_methods": sorted(self.allowed_methods),
            "env_prefix": self.env_prefix,
            "allowed_tags": sorted(self.allowed_tags),
            "allowed_operations": sorted(self.allowed_operations),
            "denied_operations": sorted(self.denied_operations),
        }
        manifest_file = output_path / "generation_manifest.json"
        manifest_file.write_text(json.dumps(manifest, indent=2))


        return {
            "server_file": str(server_file),
            "runtime_file": str(runtime_file),
            "config_file": str(config_file),
            "inventory_file": str(inventory_file),
            "env_file": str(env_file),
            "readme_file": str(readme_file),
            "skill_file": str(skill_file),
            "manifest_file": str(manifest_file),
            "tool_count": len(endpoints),
            "source_tool_count": len(all_endpoints),
            "server_name": self.server_name,
        }

    def generate_profiles(
        self,
        profiles: dict[str, dict],
        output_root: str | Path,
    ) -> dict[str, dict]:
        """Generate independently scoped servers from one analyzed API."""
        results = {}
        root = Path(output_root)
        for profile_name, options in profiles.items():
            options = dict(options)
            server_name = options.pop("server_name", f"{self.server_name}-{profile_name}")
            env_prefix = options.pop(
                "env_prefix",
                f"{self.env_prefix}_{_sanitize_name(profile_name).upper()}",
            )
            profile = MCPServerGenerator(
                self.analyzer,
                server_name=server_name,
                env_prefix=env_prefix,
                allow_writes=options.pop("allow_writes", False),
                allowed_tags=options.pop("allowed_tags", set()),
                allowed_operations=options.pop("allowed_operations", set()),
                denied_operations=options.pop("denied_operations", set()),
                allowed_methods=options.pop("allowed_methods", set()),
                max_documented_tools=options.pop(
                    "max_documented_tools", self.max_documented_tools
                ),
            )
            if options:
                unknown = ", ".join(sorted(options))
                raise TypeError(f"Unknown profile options: {unknown}")
            results[profile_name] = profile.generate(root / profile_name)
        return results

    def _generate_tool(self, endpoint: EndpointInfo) -> str:
        bindings, body_name = _parameter_bindings(endpoint)
        func_name = _sanitize_name(endpoint.operation_id) or _sanitize_name(
            f"{endpoint.method}_{endpoint.path}"
        )
        params = _build_param_signature(endpoint)
        summary = (endpoint.summary or endpoint.description or f"{endpoint.method} {endpoint.path}")
        summary = summary.replace('"""', "'''").replace("\n", " ")[:500]
        path_template = _build_url_template(endpoint.path, bindings)
        query_code = _build_parameter_map(bindings, "query", "query_params")
        header_code = _build_parameter_map(bindings, "header", "header_params")
        cookie_code = _build_parameter_map(bindings, "cookie", "cookie_params")
        body_expression = f"{body_name} if {body_name} else None" if body_name else "None"
        content_type = endpoint.request_body.get("content_type", "application/json") if endpoint.request_body else "application/json"

        return f'''@mcp.tool()
def {func_name}({params}) -> dict:
    """{summary}"""
    path = f"{path_template}"
{query_code}
{header_code}
{cookie_code}
    request_body = {body_expression}
    return _request(
        {json.dumps(endpoint.method)},
        path,
        params=query_params,
        headers=header_params,
        cookies=cookie_params,
        body=request_body,
        content_type={json.dumps(content_type)},
        operation_id={json.dumps(endpoint.operation_id)},
        tags={json.dumps(endpoint.tags or [])},
    )
'''

    def _generate_mcp_config(self, server_file: str) -> dict:
        return {
            "mcpServers": {
                self.server_name: {
                    "command": "python3",
                    "args": [server_file],
                    "env": {
                        f"{self.env_prefix}_BASE_URL": self.analyzer.base_url,
                        f"{self.env_prefix}_ALLOW_WRITES": "true"
                        if self.allow_writes
                        else "false",
                        f"{self.env_prefix}_ALLOWED_METHODS": ",".join(
                            sorted(self.allowed_methods)
                        ),
                        f"{self.env_prefix}_ALLOWED_TAGS": ",".join(
                            sorted(self.allowed_tags)
                        ),
                        f"{self.env_prefix}_ALLOWED_OPERATIONS": ",".join(
                            sorted(self.allowed_operations)
                        ),
                        f"{self.env_prefix}_DENIED_OPERATIONS": ",".join(
                            sorted(self.denied_operations)
                        ),
                    },
                }
            }
        }

    def _generate_inventory(self, endpoints: list[EndpointInfo]) -> list[dict]:
        inventory = []
        for endpoint in endpoints:
            bindings, _ = _parameter_bindings(endpoint)
            inventory.append(
                {
                    "name": _sanitize_name(endpoint.operation_id),
                    "operation_id": endpoint.operation_id,
                    "method": endpoint.method,
                    "path": endpoint.path,
                    "summary": endpoint.summary,
                    "tags": endpoint.tags,
                    "parameters": [
                        {
                            "name": local_name,
                            "original_name": parameter.name,
                            "location": parameter.location,
                            "required": parameter.required,
                            "type": _schema_to_python_type(parameter.schema),
                        }
                        for parameter, local_name in bindings
                    ],
                    "has_request_body": endpoint.request_body is not None,
                    "content_type": endpoint.request_body.get("content_type")
                    if endpoint.request_body
                    else None,
                    "request_body_schema": endpoint.request_body.get("schema")
                    if endpoint.request_body
                    else None,
                }
            )
        return inventory

    def _generate_readme(
        self,
        summary: dict,
        endpoints: list[EndpointInfo],
        documented_endpoints: list[EndpointInfo],
    ) -> str:
        tag_counts: dict[str, int] = {}
        for endpoint in endpoints:
            for tag in endpoint.tags or ["untagged"]:
                tag_counts[tag] = tag_counts.get(tag, 0) + 1
        lines = [
            f"# {self.server_name} MCP Server",
            "",
            "Generated by **MCP-Anything**.",
            "",
            f"**API:** {summary['title']} v{summary['version']}",
            f"**Base URL:** `{summary['base_url']}`",
            f"**Exposed tools:** {len(endpoints)}",
            f"**Writes enabled at generation:** `{self.allow_writes}`",
            "",
            "## Configuration",
            "",
            f"Set `{self.env_prefix}_EMAIL` and `{self.env_prefix}_PASSWORD` in the process environment, or use `{self.env_prefix}_API_KEY`.",
            "Writes and capabilities are disabled by default at runtime.",
            "",
            "## Tool groups",
            "",
        ]
        lines.extend(f"- **{tag}**: {count}" for tag, count in sorted(tag_counts.items()))
        if documented_endpoints:
            lines.extend(["", "## Representative tools", "", "| Tool | Method | Path |", "|---|---|---|"])
            lines.extend(
                f"| `{_sanitize_name(endpoint.operation_id)}` | {endpoint.method} | `{endpoint.path}` |"
                for endpoint in documented_endpoints
            )
        if len(documented_endpoints) < len(endpoints):
            lines.extend(["", f"Only the first {len(documented_endpoints)} tools are listed; see `tools_inventory.json` for the complete inventory."])
        return textwrap.dedent("\n".join(lines) + "\n")
