"""
trello - MCP Server
Auto-generated by MCP-Anything from specs/trello-openapi.yaml

Title: Trello REST API
Version: 1.0.0
Base URL: https://api.trello.com/1
Endpoints: 22
"""

import json
import os
from typing import Any, Literal, Optional

import httpx
from fastmcp import FastMCP

# ─── Configuration ──────────────────────────────────────────────────────

BASE_URL = os.environ.get("TRELLO_BASE_URL", "https://api.trello.com/1")
API_KEY = os.environ.get("TRELLO_API_KEY", "")

# ─── HTTP Client ────────────────────────────────────────────────────────

def _get_headers() -> dict:
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if API_KEY:
        headers["Authorization"] = f"Bearer {API_KEY}"
    return headers

def _request(method: str, path: str, params: dict = None, body: dict = None) -> dict:
    """Make an HTTP request and return parsed JSON."""
    url = BASE_URL.rstrip("/") + path
    with httpx.Client(timeout=30) as client:
        resp = client.request(
            method=method,
            url=url,
            params=params or {},
            json=body if body else None,
            headers=_get_headers(),
        )
        resp.raise_for_status()
        if resp.status_code == 204:
            return {"status": "success", "code": 204}
        try:
            return resp.json()
        except Exception:
            return {"status": "success", "text": resp.text[:2000]}

# ─── MCP Server ─────────────────────────────────────────────────────────

mcp = FastMCP("trello")

@mcp.tool()
def getmymember(key: str, token: str, fields: str = "") -> dict:
    """
    Get current authenticated member
    
    Returns the member profile for the authenticated user.
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/members/me"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def getmember(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get a member by ID or username
    
    
        id: Member ID or username
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/members/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def getmemberboards(id: str, key: str, token: str, fields: str = "", filter: Literal['all', 'closed', 'none', 'open', 'starred', 'unpinned'] = 'open') -> dict:
    """
    Get all boards for a member
    
    
        id: Member ID or username
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
        filter: filter (query, optional)
    """
    path = f"/members/{id}/boards"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    if filter is not None and filter != '':
        query_params["filter"] = filter
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def getboard(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get a board by ID
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/boards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def updateboard(id: str, key: str, token: str, body: dict = {}) -> dict:
    """
    Update a board
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/boards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("PUT", path, params=query_params, body=request_body)

@mcp.tool()
def deleteboard(id: str, key: str, token: str) -> dict:
    """
    Delete a board
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
    """
    path = f"/boards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = None
    return _request("DELETE", path, params=query_params, body=request_body)

@mcp.tool()
def createboard(key: str, token: str, body: dict = {}) -> dict:
    """
    Create a new board
    
    
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/boards"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("POST", path, params=query_params, body=request_body)

@mcp.tool()
def getboardlists(id: str, key: str, token: str, filter: Literal['all', 'closed', 'none', 'open'] = 'open', fields: str = "") -> dict:
    """
    Get all lists on a board
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
        filter: filter (query, optional)
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/boards/{id}/lists"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if filter is not None and filter != '':
        query_params["filter"] = filter
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def getboardcards(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get all cards on a board
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/boards/{id}/cards"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def createboardlabel(id: str, key: str, token: str, body: dict = {}) -> dict:
    """
    Create a label on a board
    
    
        id: Board ID
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/boards/{id}/labels"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("POST", path, params=query_params, body=request_body)

@mcp.tool()
def getlist(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get a list by ID
    
    
        id: List ID
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/lists/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def updatelist(id: str, key: str, token: str, body: dict = {}) -> dict:
    """
    Update a list (rename, archive, move)
    
    
        id: List ID
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/lists/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("PUT", path, params=query_params, body=request_body)

@mcp.tool()
def createlist(key: str, token: str, body: dict = {}) -> dict:
    """
    Create a new list on a board
    
    
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/lists"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("POST", path, params=query_params, body=request_body)

@mcp.tool()
def getlistcards(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get all cards in a list
    
    
        id: List ID
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/lists/{id}/cards"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def getcard(id: str, key: str, token: str, fields: str = "") -> dict:
    """
    Get a card by ID
    
    
        id: Card ID
        key: Trello API key
        token: Trello API token
        fields: Comma-separated list of fields to return (e.g. "name,id,desc")
    """
    path = f"/cards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if fields is not None and fields != '':
        query_params["fields"] = fields
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def updatecard(id: str, key: str, token: str, body: dict = {}) -> dict:
    """
    Update a card (rename, move, add labels, set due date, etc.)
    
    
        id: Card ID
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/cards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("PUT", path, params=query_params, body=request_body)

@mcp.tool()
def deletecard(id: str, key: str, token: str) -> dict:
    """
    Delete a card
    
    
        id: Card ID
        key: Trello API key
        token: Trello API token
    """
    path = f"/cards/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = None
    return _request("DELETE", path, params=query_params, body=request_body)

@mcp.tool()
def createcard(key: str, token: str, body: dict = {}) -> dict:
    """
    Create a new card in a list
    
    
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/cards"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("POST", path, params=query_params, body=request_body)

@mcp.tool()
def getlabel(id: str, key: str, token: str) -> dict:
    """
    Get a label by ID
    
    
        id: Label ID
        key: Trello API key
        token: Trello API token
    """
    path = f"/labels/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

@mcp.tool()
def updatelabel(id: str, key: str, token: str, body: dict = {}) -> dict:
    """
    Update a label (rename, change color)
    
    
        id: Label ID
        key: Trello API key
        token: Trello API token
        body: Request body as a dict
    """
    path = f"/labels/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = body if body else None
    return _request("PUT", path, params=query_params, body=request_body)

@mcp.tool()
def deletelabel(id: str, key: str, token: str) -> dict:
    """
    Delete a label from a board
    
    
        id: Label ID
        key: Trello API key
        token: Trello API token
    """
    path = f"/labels/{id}"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    request_body = None
    return _request("DELETE", path, params=query_params, body=request_body)

@mcp.tool()
def search(key: str, token: str, query: str, idorganizations: str = "", idboards: str = "", modeltypes: Literal['actions', 'boards', 'cards', 'members', 'organizations'] = "", board_fields: str = "", cards_limit: int = 10, boards_limit: int = 10) -> dict:
    """
    Search across boards, cards, and members
    
    
        key: Trello API key
        token: Trello API token
        query: Search query string
        idorganizations: Comma-separated org IDs to limit search
        idboards: Comma-separated board IDs to limit search
        modeltypes: Comma-separated model types to search
        board_fields: Fields for board results
        cards_limit: Max card results
        boards_limit: Max board results
    """
    path = f"/search"
    query_params = {}
    if key is not None and key != '':
        query_params["key"] = key
    if token is not None and token != '':
        query_params["token"] = token
    if query is not None and query != '':
        query_params["query"] = query
    if idorganizations is not None and idorganizations != '':
        query_params["idOrganizations"] = idorganizations
    if idboards is not None and idboards != '':
        query_params["idBoards"] = idboards
    if modeltypes is not None and modeltypes != '':
        query_params["modelTypes"] = modeltypes
    if board_fields is not None and board_fields != '':
        query_params["board_fields"] = board_fields
    if cards_limit is not None and cards_limit != '':
        query_params["cards_limit"] = cards_limit
    if boards_limit is not None and boards_limit != '':
        query_params["boards_limit"] = boards_limit
    request_body = None
    return _request("GET", path, params=query_params, body=request_body)

